# config.yml

backend:
  name: github
  repo: whereshj/codeforboston.org
  branch: master # Branch to update (optional; defaults to master)
  site_domain: whereshj.github.io/codeforboston.org/
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }